"use client";
import {useMemo,useState} from "react";
import {uid,type LocalBooking,type LocalStudent} from "@/lib/local-coach-data";
const pad=(value:number)=>String(value).padStart(2,"0");
const keyFor=(date:Date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const dateFor=(key:string)=>new Date(`${key}T12:00:00`);
type ViewMode="month"|"week"|"day";
export function LocalCalendar({students,bookings,onChange}:{students:LocalStudent[];bookings:LocalBooking[];onChange:(bookings:LocalBooking[])=>void}){
 const today=new Date(),[selectedDate,setSelectedDate]=useState(keyFor(today)),[month,setMonth]=useState(new Date(today.getFullYear(),today.getMonth(),1)),[view,setView]=useState<ViewMode>("month");
 const eventsByDate=useMemo(()=>Object.groupBy(bookings,booking=>booking.date),[bookings]);
 const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),cells:Array<Date|null>=Array(first.getDay()).fill(null);
 for(let day=1;day<=last.getDate();day++)cells.push(new Date(month.getFullYear(),month.getMonth(),day));while(cells.length%7)cells.push(null);
 const selected=dateFor(selectedDate),selectedBookings=(eventsByDate[selectedDate]||[]).toSorted((a,b)=>a.time.localeCompare(b.time));
 const monday=new Date(selected);monday.setDate(selected.getDate()-((selected.getDay()+6)%7));
 const visibleDates=Array.from({length:7},(_,index)=>{const date=new Date(view==="week"?monday:selected);date.setDate(date.getDate()+index-(view==="day"?3:0));return date});
 const label=selected.toLocaleDateString("zh-TW",{year:"numeric",month:"long",day:"numeric",weekday:"long"});
 return <section className="calendar-v2" id="calendar">
  <div className="calendar-toolbar"><div><div className="eyebrow">預約管理 · 本機資料</div><h2>{view==="month"?month.toLocaleDateString("zh-TW",{year:"numeric",month:"long"}):label}</h2></div><div className="calendar-view-switch" aria-label="行事曆顯示模式">{(["month","week","day"] as ViewMode[]).map(mode=><button type="button" className={view===mode?"active":""} onClick={()=>setView(mode)} key={mode}>{{month:"月",week:"週",day:"日"}[mode]}</button>)}</div></div>
  {view==="month"?<div className="compact-month"><div className="month-controls"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>上個月</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>下個月</button></div><div className="calendar-grid weekdays">{["日","一","二","三","四","五","六"].map(day=><div key={day}>{day}</div>)}</div><div className="calendar-grid">{cells.map((date,index)=>date?<button type="button" className={`compact-day ${selectedDate===keyFor(date)?"selected":""}`} onClick={()=>setSelectedDate(keyFor(date))} key={keyFor(date)}><strong>{date.getDate()}</strong><small className={(eventsByDate[keyFor(date)]||[]).length?"available":"full"}>{(eventsByDate[keyFor(date)]||[]).length?`${eventsByDate[keyFor(date)]!.length} 堂預約`:"尚無預約"}</small></button>:<div className="compact-day blank" key={`blank-${index}`}/>)}</div><div className="availability-legend"><span><i className="available"/>已有學生預約</span><span><i/>尚無預約</span></div></div>:<div className="date-strip">{visibleDates.map(date=><button type="button" className={keyFor(date)===selectedDate?"selected":""} onClick={()=>setSelectedDate(keyFor(date))} key={keyFor(date)}><span>{["日","一","二","三","四","五","六"][date.getDay()]}</span><strong>{date.getDate()}</strong><small>{(eventsByDate[keyFor(date)]||[]).length} 堂</small></button>)}</div>}
  <div className="selected-day-head"><div><h2>{label}</h2><p>{selectedBookings.length} 堂預約・資料儲存在這台裝置</p></div><button className="button" onClick={()=>document.getElementById("appointment-form")?.scrollIntoView({behavior:"smooth"})}>＋ 新增學生預約</button></div>
  <div className="day-schedule"><section><h3>已預約</h3>{selectedBookings.length?selectedBookings.map(booking=><article className="schedule-row booked" key={booking.id}><time>{booking.time}</time><strong>{students.find(student=>student.id===booking.studentId)?.name||"未知學生"}</strong><span>{booking.duration} 分鐘</span></article>):<p className="muted">這天目前沒有預約。</p>}</section><section><h3>本機日曆</h3><p className="muted">預約只會儲存在目前裝置，不會同步到 Google Calendar。</p>{selectedBookings.map(booking=><button className="danger-link" type="button" onClick={()=>onChange(bookings.filter(item=>item.id!==booking.id))} key={booking.id}>移除 {booking.time} 的預約</button>)}</section></div>
  <div className="card appointment-card" id="appointment-form"><h2>新增學生預約</h2>{students.length?<form className="stack" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onChange([...bookings,{id:uid(),studentId:String(form.get("studentId")),date:selectedDate,time:String(form.get("time")),duration:Number(form.get("duration"))||60,notes:String(form.get("notes")||"")}]);event.currentTarget.reset()}}><label>學生<select name="studentId" required defaultValue=""><option value="" disabled>選擇學生</option>{students.map(student=><option value={student.id} key={student.id}>{student.name}</option>)}</select></label><label>日期<input type="date" value={selectedDate} onChange={event=>setSelectedDate(event.target.value)} required/></label><div className="row"><label>開始時間<input name="time" type="time" defaultValue="10:00" required/></label><label>課程分鐘<input name="duration" type="number" min="15" step="15" defaultValue="60" required/></label></div><textarea name="notes" placeholder="預約備註（選填）"/><button>儲存在本機日曆</button></form>:<p className="muted">請先建立學生，再新增預約。</p>}</div>
 </section>
}
