"use client";
import {useEffect,useMemo,useState} from "react";
import {defaultLocalCalendarSettings,uid,type LocalBooking,type LocalPeriod,type LocalStudent} from "@/lib/local-coach-data";
const pad=(value:number)=>String(value).padStart(2,"0");
const keyFor=(date:Date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;
const dateFor=(key:string)=>new Date(`${key}T12:00:00`);
type ViewMode="month"|"week"|"day";
const settingsKey="coachlog-local-calendar-settings-v1";
const minutes=(value:string)=>{const [hour,minute]=value.split(":").map(Number);return hour*60+minute};
const clock=(value:number)=>`${pad(Math.floor(value/60))}:${pad(value%60)}`;
export function LocalCalendar({students,bookings,onChange}:{students:LocalStudent[];bookings:LocalBooking[];onChange:(bookings:LocalBooking[])=>void}){
 const today=new Date(),[selectedDate,setSelectedDate]=useState(keyFor(today)),[month,setMonth]=useState(new Date(today.getFullYear(),today.getMonth(),1)),[view,setView]=useState<ViewMode>("month"),[settingsOpen,setSettingsOpen]=useState(false),[settingsDay,setSettingsDay]=useState(today.getDay()),[duration,setDuration]=useState(60),[periods,setPeriods]=useState<Record<string,LocalPeriod[]>>(structuredClone(defaultLocalCalendarSettings.periods));
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(settingsKey)||"");if(saved.view)setView(saved.view);if(saved.duration)setDuration(saved.duration);if(saved.periods)setPeriods(saved.periods)}catch{}},[]);
 const eventsByDate=useMemo(()=>Object.groupBy(bookings,booking=>booking.date),[bookings]);
 const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),cells:Array<Date|null>=Array(first.getDay()).fill(null);
 for(let day=1;day<=last.getDate();day++)cells.push(new Date(month.getFullYear(),month.getMonth(),day));while(cells.length%7)cells.push(null);
 const selected=dateFor(selectedDate),selectedBookings=(eventsByDate[selectedDate]||[]).toSorted((a,b)=>a.time.localeCompare(b.time));
 const monday=new Date(selected);monday.setDate(selected.getDate()-((selected.getDay()+6)%7));
 const visibleDates=Array.from({length:7},(_,index)=>{const date=new Date(view==="week"?monday:selected);date.setDate(date.getDate()+index-(view==="day"?3:0));return date});
 const label=selected.toLocaleDateString("zh-TW",{year:"numeric",month:"long",day:"numeric",weekday:"long"});
 const slotsFor=(dateKey:string)=>{const date=dateFor(dateKey),result:string[]=[];for(const period of periods[String(date.getDay())]||[])for(let start=minutes(period.start);start+duration<=minutes(period.end);start+=duration){const time=clock(start),slotStart=new Date(`${dateKey}T${time}:00`),slotEnd=new Date(slotStart.getTime()+duration*60000),conflict=bookings.some(booking=>booking.date===dateKey&&new Date(`${booking.date}T${booking.time}:00`)<slotEnd&&new Date(new Date(`${booking.date}T${booking.time}:00`).getTime()+booking.duration*60000)>slotStart);if(!conflict)result.push(time)}return result};
 const availableSlots=slotsFor(selectedDate),weekdayLabels=["日","一","二","三","四","五","六"];
 return <section className="calendar-v2" id="calendar">
  <div className="calendar-toolbar"><div><div className="eyebrow">預約管理 · 本機資料</div><h2>{view==="month"?month.toLocaleDateString("zh-TW",{year:"numeric",month:"long"}):label}</h2></div><div className="calendar-view-switch" aria-label="行事曆顯示模式">{(["month","week","day"] as ViewMode[]).map(mode=><button type="button" className={view===mode?"active":""} onClick={()=>setView(mode)} key={mode}>{{month:"月",week:"週",day:"日"}[mode]}</button>)}</div></div>
  {view==="month"?<div className="compact-month"><div className="month-controls"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>上個月</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>下個月</button></div><div className="calendar-grid weekdays">{["日","一","二","三","四","五","六"].map(day=><div key={day}>{day}</div>)}</div><div className="calendar-grid">{cells.map((date,index)=>date?<button type="button" className={`compact-day ${selectedDate===keyFor(date)?"selected":""}`} onClick={()=>setSelectedDate(keyFor(date))} key={keyFor(date)}><strong>{date.getDate()}</strong><small className={(eventsByDate[keyFor(date)]||[]).length?"available":"full"}>{(eventsByDate[keyFor(date)]||[]).length?`${eventsByDate[keyFor(date)]!.length} 堂預約`:"尚無預約"}</small></button>:<div className="compact-day blank" key={`blank-${index}`}/>)}</div><div className="availability-legend"><span><i className="available"/>已有學生預約</span><span><i/>尚無預約</span></div></div>:<div className="date-strip">{visibleDates.map(date=><button type="button" className={keyFor(date)===selectedDate?"selected":""} onClick={()=>setSelectedDate(keyFor(date))} key={keyFor(date)}><span>{["日","一","二","三","四","五","六"][date.getDay()]}</span><strong>{date.getDate()}</strong><small>{(eventsByDate[keyFor(date)]||[]).length} 堂</small></button>)}</div>}
  <div className="selected-day-head"><div><h2>{label}</h2><p>{selectedBookings.length} 堂預約・資料儲存在這台裝置</p></div><button className="button" onClick={()=>document.getElementById("appointment-form")?.scrollIntoView({behavior:"smooth"})}>＋ 新增學生預約</button></div>
  <div className="day-schedule"><section><h3>已預約</h3>{selectedBookings.length?selectedBookings.map(booking=><article className="schedule-row booked" key={booking.id}><time>{booking.time}</time><strong>{students.find(student=>student.id===booking.studentId)?.name||"未知學生"}</strong><span>{booking.duration} 分鐘</span><button className="danger-link" type="button" onClick={()=>onChange(bookings.filter(item=>item.id!==booking.id))}>移除</button></article>):<p className="muted">這天目前沒有預約。</p>}</section><section><h3>可預約時段</h3>{availableSlots.length?<div className="slot-list">{availableSlots.map(slot=><button type="button" onClick={()=>{const input=document.querySelector<HTMLInputElement>('#appointment-form input[name="time"]');if(input)input.value=slot;document.getElementById("appointment-form")?.scrollIntoView({behavior:"smooth"})}} key={slot}>{slot}<small>{duration} 分鐘</small></button>)}</div>:<p className="muted">這天沒有設定可預約時段。</p>}</section></div>
  <button className="calendar-settings-toggle" type="button" onClick={()=>setSettingsOpen(open=>!open)} aria-expanded={settingsOpen}>行事曆設定：每堂 {duration} 分鐘・每週可預約時間</button>
  {settingsOpen&&<section className="card calendar-settings"><div className="settings-heading"><div><span className="settings-kicker">排程偏好</span><h3>行事曆設定</h3><p>設定每週固定開放時段，一天可以加入多個不連續時段。</p></div><button className="settings-close" type="button" onClick={()=>setSettingsOpen(false)}>收起設定</button></div><div className="settings-basics"><label>預設檢視<select value={view} onChange={event=>setView(event.target.value as ViewMode)}><option value="month">月檢視</option><option value="week">週檢視</option><option value="day">日檢視</option></select></label><label>每堂課長度<input type="number" min="15" step="15" value={duration} onChange={event=>setDuration(Math.max(15,Number(event.target.value)||60))}/><small>分鐘</small></label></div><section className="weekly-periods"><div className="periods-heading"><div><h4>每週可預約時間</h4><p>選擇星期後新增或編輯時段</p></div></div><div className="weekday-tabs" role="tablist">{weekdayLabels.map((label,day)=><button type="button" role="tab" aria-selected={settingsDay===day} className={settingsDay===day?"active":""} onClick={()=>setSettingsDay(day)} key={day}><strong>週{label}</strong><small>{periods[String(day)]?.length?`${periods[String(day)].length} 段`:"休息"}</small></button>)}</div><div className="selected-weekday"><div className="selected-weekday-head"><div><h4>週{weekdayLabels[settingsDay]}</h4><p>{periods[String(settingsDay)]?.length?"學生只會看到以下時段可預約。":"目前設定為休息日。"}</p></div>{periods[String(settingsDay)]?.length>0&&<button className="day-off-button" type="button" onClick={()=>setPeriods(current=>({...current,[settingsDay]:[]}))}>設為休息日</button>}</div><div className="period-list">{(periods[String(settingsDay)]||[]).map((period,index)=><div className="period-card" key={index}><span className="period-number">時段 {index+1}</span><label><span>開始</span><input type="time" value={period.start} onChange={event=>setPeriods(current=>({...current,[settingsDay]:current[String(settingsDay)].map((item,i)=>i===index?{...item,start:event.target.value}:item)}))}/></label><span className="period-arrow">→</span><label><span>結束</span><input type="time" value={period.end} onChange={event=>setPeriods(current=>({...current,[settingsDay]:current[String(settingsDay)].map((item,i)=>i===index?{...item,end:event.target.value}:item)}))}/></label><button className="remove-period" type="button" onClick={()=>setPeriods(current=>({...current,[settingsDay]:current[String(settingsDay)].filter((_,i)=>i!==index)}))}>移除</button></div>)}<button className="add-period" type="button" onClick={()=>setPeriods(current=>({...current,[settingsDay]:[...(current[String(settingsDay)]||[]),{start:"09:00",end:"12:00"}]}))}>＋ 新增一個時段</button></div></div></section><div className="settings-actions"><button className="button light" type="button" onClick={()=>setSettingsOpen(false)}>取消</button><button type="button" onClick={()=>{localStorage.setItem(settingsKey,JSON.stringify({view,duration,periods}));setSettingsOpen(false)}}>儲存行事曆設定</button></div></section>}
  <div className="card appointment-card" id="appointment-form"><h2>新增學生預約</h2>{students.length?<form className="stack" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onChange([...bookings,{id:uid(),studentId:String(form.get("studentId")),date:selectedDate,time:String(form.get("time")),duration:Number(form.get("duration"))||duration,notes:String(form.get("notes")||"")}]);event.currentTarget.reset()}}><label>學生<select name="studentId" required defaultValue=""><option value="" disabled>選擇學生</option>{students.map(student=><option value={student.id} key={student.id}>{student.name}</option>)}</select></label><label>日期<input type="date" value={selectedDate} onChange={event=>setSelectedDate(event.target.value)} required/></label><div className="row"><label>開始時間<input name="time" type="time" defaultValue={availableSlots[0]||"10:00"} required/></label><label>課程分鐘<input name="duration" type="number" min="15" step="15" defaultValue={duration} required/></label></div><textarea name="notes" placeholder="預約備註（選填）"/><button>儲存在本機日曆</button></form>:<p className="muted">請先建立學生，再新增預約。</p>}</div>
 </section>
}
